import Head from "next/head";
import Link from "next/link";
import React, { useState } from "react";
// import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button, Container } from "@chakra-ui/react";
import { CloseButton } from "@chakra-ui/close-button";
import { Center, Link as ChakraLink } from "@chakra-ui/react";
import { Text, Stack, Flex } from "@chakra-ui/react";
import {
  AiFillGithub,
  AiOutlineMail,
  AiFillLinkedin,
  AiOutlineTwitter,
} from "react-icons/ai";
import { BsMastodon } from "react-icons/bs";
import { Image } from "@chakra-ui/react";
import { GoCalendar } from "react-icons/go"
// import { InlineWidget } from "react-calendly";
// import { PopupButton } from "react-calendly";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let [loaded, setLoaded] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link
          href="https://assets.calendly.com/assets/external/widget.css"
          rel="stylesheet"
        />
        <script
          src="https://assets.calendly.com/assets/external/widget.js"
          type="text/javascript"
          async
        ></script> */}
        {/* <script src="/calendly-widget.js" type="text/javascript"></script> */}
      </Head>
      <div>
        <Center>
          {/* <Image
                className="artistimg"
                src="https://unlockyoursound.com/wp-content/uploads/2023/02/chris-500-2.jpeg"
                alt="artistprofile"
              /> */}
          <Image
            borderRadius="100"
            borderStyle="solid"
            borderColor="white"
            borderWidth={2}
            boxSize="200px"
            src="https://unlockyoursound.com/wp-content/uploads/2023/02/chris-500-2.jpeg"
            alt="Christopher Carvalho"
            mt={100}
          />
        </Center>
        <br></br>
        <Center>
          <Text></Text>
          <Text></Text>
        </Center>
        <Center>
          <Stack spacing={6} maxW={350}>
            <Text fontSize="3xl" align="center" justify="center">
              Hi, I&apos;m Christopher.
            </Text>
            <Text fontSize="2xl" align="center" justify="center">
              Content writer, educator, and self-taught developer.
            </Text>
            <Text fontSize="1xl" align="center" justify="center">
              I use React, ChakraUI, and Django Rest Framework.
            </Text>
            <Center>
              <Link
                href="/work"
                legacyBehavior
                style={{ position: "relative" }}
              >
                <Button
                  colorScheme="blue"
                  // onClick={() => setLoaded((loaded = !loaded))}
                  minW={300}
                >
                  View Work
                </Button>
              </Link>
            </Center>
            <Container mt={0} pt={0}></Container>
          </Stack>
        </Center>
        <Container mt={0} pt={0} maxW={340}>
          <Flex isInline gap={3}>
            <ChakraLink href="https://github.com/carvalhochris" isExternal>
              <AiFillGithub size={30} />
            </ChakraLink>
            <ChakraLink href="mailto:hello@christophercarvalho.com" isExternal>
              <AiOutlineMail size={30} />
            </ChakraLink>
            <ChakraLink
              href="https://www.linkedin.com/in/christopher-carvalho-music/"
              isExternal
            >
              <AiFillLinkedin size={30} />
            </ChakraLink>
            <ChakraLink href="https://twitter.com/mkdir_cc" isExternal>
              <AiOutlineTwitter size={30} />
            </ChakraLink>
            <ChakraLink
              href="https://mastodon.social/@carvalhochris"
              isExternal
            >
              <BsMastodon size={30} />
            </ChakraLink>
            <ChakraLink
              href="https://calendly.com/christopher-carvalho/30-minute-meeting-portfolio"
              isExternal
            >
              <GoCalendar size={30} />
            </ChakraLink>
          </Flex>
        </Container>
      </div>
    </>
  );
}
