import Head from "next/head";
import React, { useState } from "react";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Button, Container, Link } from "@chakra-ui/react";
import { CloseButton } from "@chakra-ui/close-button";
import { Center } from "@chakra-ui/react";
import { Text, Stack, Flex } from "@chakra-ui/react";
import { AiFillGithub, AiOutlineMail, AiFillLinkedin } from "react-icons/ai";
import { BsMastodon } from "react-icons/bs";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let [loaded, setLoaded] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {loaded && (
          <div>
            <Center>
              <Stack pt={5}>
                {/* <GetCards /> */}
                <Center>
                  <p className="emoji">😀</p>
                </Center>
                <Center>
                  <CloseButton
                    onClick={() => setLoaded((loaded = !loaded))}
                    color="blue.500"
                    mb={200}
                  />
                </Center>
              </Stack>
            </Center>
          </div>
        )}
        {loaded || (
          <div>
            <Center>
              <img
                className="artistimg"
                src="https://unlockyoursound.com/wp-content/uploads/2023/02/chris-500-2.jpeg"
                alt="artistprofile"
              />
            </Center>
            <br></br>
            <Center>
              <Text></Text>
              <Text></Text>
            </Center>
            <Center>
              <Stack spacing={6} maxW={350}>
                <Text fontSize="3xl">Hi, I'm Christopher.</Text>
                <Text fontSize="2xl">
                  Content writer, educator, and self-taught developer.
                </Text>
                <Text fontSize="1xl">
                  I use React, ChakraUI, and Django Rest Framework.
                </Text>
                <Center>
                  <Button
                    colorScheme="blue"
                    onClick={() => setLoaded((loaded = !loaded))}
                    minW={300}
                  >
                    View Portfolio
                  </Button>
                </Center>
                <Container mt={0} pt={0}></Container>
              </Stack>
            </Center>
            <Container mt={0} pt={0} maxW={340}>
              <Flex isInline gap={3}>
                <Link href="https://github.com/carvalhochris" isExternal>
                  <AiFillGithub size={30} />
                </Link>
                <Link href="mailto:hello@christophercarvalho.com" isExternal>
                  <AiOutlineMail size={30} />
                </Link>
                <Link
                  href="https://www.linkedin.com/in/christopher-carvalho-music/"
                  isExternal
                >
                  <AiFillLinkedin size={30} />
                </Link>
                <a
                  rel="me"
                  target="#"
                  href="https://mastodon.social/@carvalhochris"
                >
                  <BsMastodon size={30} />
                </a>
              </Flex>
            </Container>
          </div>
        )}
      </main>
    </>
  );
}
